### ISSUE TITLE
Notes fields in Interactions tab need to have a scroll function

### ISSUE THREAD

**Issue by mrmarkwell** [mrmarkwell/evergreendb#115]
title

**Comment by jdb098** [comment]
notes section is a textarea which has scrolling by default. It could be that we just need to add some placeholder so that you can see scrolling even when user hasn't added any notes (can't see the scrolling in a blank textarea). I'll also look into the packaged app, could be it isn't scrolling for some reason

**Comment by jdb098** [comment]
Wasn't looking at the right comment area. Many comments are just inputs and should be changed to text fields. Also, all the text fields should be initialized a 2 or 3 lines available so that scrolling is easily seen

**Comment by jdb098** [comment]
#132 merged
